### ISSUE TITLE
Make it so it can render above y = 256

### ISSUE THREAD

**Issue by XboxBedrock** [tf2mandeokyi/MapDisplayer4BTE#2]
cmon not everywhere is under y= 256 we have cubichunks for a reason

**Comment by tf2mandeokyi** [comment]
Implemented [`2390d11`](https://github.com/tf2mandeokyi/MapDisplayer4BTE/commit/2390d11fafc9685c4bd9b91b9c76ef880fb5b87c)

![image](https://user-images.githubusercontent.com/57130819/105390243-2c01e380-5c5c-11eb-965d-5cc298f900c6.png)
